jobs:
  test-linux:
    name: Test on Linux
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Image
        run: "\tdocker build --tag bash-object:bash-version ."
      - name: Run Tests
        run: "\ttime docker run bash-object:bash-version --tap tests"
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
name: Test Code
'on':
  - push
  - pull_request
permissions: read-all
